export const AGENT_CONFIG_REPOSITORY = Symbol('AGENT_CONFIG_REPOSITORY');
export const AGENT_HOST_DB = Symbol('AGENT_HOST_DB');
export const ALERT_RECORDER = Symbol('ALERT_RECORDER');
export const DEFAULT_PROVIDER_AVAILABLE = Symbol('DEFAULT_PROVIDER_AVAILABLE');
