export {
  CONV_ATTACHMENT_MIME_ALLOWLIST,
  CONV_ATTACHMENT_BYTES_MAX,
  CONV_ATTACHMENT_PER_MESSAGE_MAX,
} from '@getmunin/types';

export const CONV_ATTACHMENT_PENDING_PER_SESSION_MAX = 10;

export const CONV_ATTACHMENT_INBOUND_BYTES_MIN = 4 * 1024;

export const CONV_ATTACHMENT_INBOUND_EDGE_MIN_PX = 32;
