import type { Strings } from './types.ts';

const cs: Strings = {
  launcherAriaLabel: 'Otevřít chat',
  closeAriaLabel: 'Zavřít',
  backAriaLabel: 'Zpět',
  messageAriaLabel: 'Zpráva',
  sendAriaLabel: 'Odeslat',
  agentTypingAriaLabel: 'Agent píše',
  newConversation: 'Nová konverzace',
  conversation: 'Konverzace',
  onlineNow: 'Právě online',
  defaultTeammateName: 'Člen týmu',
  typicallyReplies: 'obvykle odpoví během několika minut',
  statusReconnecting: 'Znovu se připojuji…',
  statusDisconnected: 'Odpojeno.',
  saveThreadEyebrow: 'Uložit tuto konverzaci',
  saveThreadBlurb: 'Nechte nám e-mail a konverzaci uložíme, i když okno zavřete.',
  saveThreadCta: 'Uložit →',
  saveThreadSkip: 'Teď ne',
  saveThreadDoneEyebrow: '● Uloženo',
  saveThreadDoneTemplate: 'Napíšeme vám na {email}, jestli se tu objeví něco nového.',
  emailPlaceholder: 'vy@firma.cz',
  composerPlaceholder: 'Napište zprávu…',
  defaultEyebrow: 'Běží na Munin',
  defaultGreeting: 'Dobrý den. Jak můžeme pomoct?',
  defaultTitle: 'Napište nám',
  welcomeRepliesInstantly: 'Odpoví hned',
  startConversationLabel: 'Začít konverzaci',
  startConversationSub: 'Hned se do toho pustí agent.',
  conversationsHeader: 'Vaše konverzace',
  emptyConversationsTitle: 'Zatím žádné konverzace',
  emptyConversationsSub: 'Začněte nahoře a příště ji najdete tady.',
  poweredBy: 'Běží na',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'člověk',
  timeNow: 'teď',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} d',
  timeWeek: '{n} týd',
  timeMonth: '{n} měs',
  voiceCallLabel: 'Zavolat',
  voiceStartAriaLabel: 'Začít hlasový hovor',
  voiceEndAriaLabel: 'Ukončit hlasový hovor',
  voiceMinimizeAriaLabel: 'Zpět do chatu (hovor zůstane aktivní)',
  voiceResumeAriaLabel: 'Zpět do hovoru',
  voiceConnecting: 'Připojuji…',
  voiceLive: 'Live',
  voiceHint: 'Hlas jde přes tento widget — žádné telefonní číslo, žádná aplikace.',
  voiceMute: 'Ztlumit',
  voiceMuted: 'Ztlumeno',
  voiceEnd: 'Ukončit',
  voiceBackToChat: 'Zpět do chatu',
  voiceOnCallWithTemplate: 'Hovor: {who}',
  voiceTapToReturn: 'Klepnutím se vrátíte',
  voiceFailed: 'Hlasový hovor se nezdařil',
  productViewLabel: 'Zobrazit',
  attachAriaLabel: 'Přidat obrázek',
  attachDropHint: 'Přetáhněte obrázek sem',
  attachUploading: 'Nahrávání…',
  attachFailed: 'Obrázek se nepodařilo nahrát. Zkuste to znovu.',
  sendFailed: 'Zprávu se nepodařilo odeslat. Zkuste to znovu.',
  attachRemoveAriaLabel: 'Odebrat obrázek',
  attachTooMany: 'Můžete přidat až {n} obrázků.',
  attachTypeRejected: 'Přijímáme PNG, JPEG, GIF a WebP.',
  attachTooLarge: 'Obrázek musí mít méně než {n} MB.',
  attachmentUnavailable: 'Obrázek už není dostupný',
  lightboxCloseAriaLabel: 'Zavřít obrázek',
};

export default cs;
