import type { Strings } from './types.ts';

const da: Strings = {
  launcherAriaLabel: 'Åbn chat',
  closeAriaLabel: 'Luk',
  backAriaLabel: 'Tilbage',
  messageAriaLabel: 'Besked',
  sendAriaLabel: 'Send',
  agentTypingAriaLabel: 'Agenten skriver',
  newConversation: 'Ny samtale',
  conversation: 'Samtale',
  onlineNow: 'Online nu',
  defaultTeammateName: 'Teammedlem',
  typicallyReplies: 'svarer typisk inden for få minutter',
  statusReconnecting: 'Genopretter forbindelse…',
  statusDisconnected: 'Forbindelse afbrudt.',
  saveThreadEyebrow: 'Gem denne samtale',
  saveThreadBlurb: 'Skriv din e-mail, så gemmer vi samtalen, hvis du lukker vinduet.',
  saveThreadCta: 'Gem →',
  saveThreadSkip: 'Ikke nu',
  saveThreadDoneEyebrow: '● Gemt',
  saveThreadDoneTemplate: 'Vi sender dig en e-mail på {email}, hvis noget nyt sker her.',
  emailPlaceholder: 'dig@firma.dk',
  composerPlaceholder: 'Skriv en besked…',
  defaultEyebrow: 'Drevet af Munin',
  defaultGreeting: 'Hej. Hvad kan vi hjælpe med?',
  defaultTitle: 'Chat med os',
  welcomeRepliesAboutHtml: 'Svar inden for ca. <strong>2 min</strong>',
  startConversationLabel: 'Start en samtale',
  startConversationSub: 'Vi sætter en agent på sagen med det samme.',
  conversationsHeader: 'Dine samtaler',
  emptyConversationsTitle: 'Ingen samtaler endnu',
  emptyConversationsSub: 'Start en ovenfor, så vises den her næste gang.',
  poweredBy: 'Drevet af',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'menneske',
  timeNow: 'nu',
  timeMin: '{n}m',
  timeHour: '{n}t',
  timeDay: '{n}d',
  timeWeek: '{n}u',
  timeMonth: '{n}mdr',
  voiceCallLabel: 'Ring',
  voiceStartAriaLabel: 'Start taleopkald',
  voiceEndAriaLabel: 'Afslut taleopkald',
  voiceMinimizeAriaLabel: 'Tilbage til chat (behold opkaldet aktivt)',
  voiceResumeAriaLabel: 'Tilbage til opkaldet',
  voiceConnecting: 'Forbinder…',
  voiceLive: 'Live',
  voiceHint: 'Tale går gennem denne widget — intet telefonnummer, ingen app.',
  voiceMute: 'Mute',
  voiceMuted: 'Mutet',
  voiceEnd: 'Afslut',
  voiceBackToChat: 'Tilbage til chat',
  voiceOnCallWithTemplate: 'I opkald med {who}',
  voiceTapToReturn: 'Tryk for at vende tilbage',
  voiceFailed: 'Taleopkald mislykkedes',
};

export default da;
