import type { Strings } from './types.js';

const de: Strings = {
  launcherAriaLabel: 'Chat öffnen',
  closeAriaLabel: 'Schließen',
  backAriaLabel: 'Zurück',
  messageAriaLabel: 'Nachricht',
  sendAriaLabel: 'Senden',
  agentTypingAriaLabel: 'Agent schreibt',
  newConversation: 'Neue Konversation',
  conversation: 'Konversation',
  onlineNow: 'Jetzt online',
  defaultTeammateName: 'Teammitglied',
  typicallyReplies: 'antwortet üblicherweise innerhalb weniger Minuten',
  statusReconnecting: 'Verbindung wird wiederhergestellt…',
  statusDisconnected: 'Verbindung getrennt.',
  saveThreadEyebrow: 'Diese Unterhaltung speichern',
  saveThreadBlurb: 'Hinterlassen Sie Ihre E-Mail, dann bewahren wir die Unterhaltung auf, falls Sie das Fenster schließen.',
  saveThreadCta: 'Speichern →',
  saveThreadSkip: 'Nicht jetzt',
  saveThreadDoneEyebrow: '● Gespeichert',
  saveThreadDoneTemplate: 'Wir schreiben Ihnen an {email}, sobald hier etwas Neues passiert.',
  emailPlaceholder: 'sie@firma.de',
  composerPlaceholder: 'Nachricht schreiben…',
  defaultEyebrow: 'Bereitgestellt von Munin',
  defaultGreeting: 'Hallo. Wie können wir helfen?',
  defaultTitle: 'Mit uns chatten',
  welcomeRepliesAboutHtml: 'Antwort in etwa <strong>2 Min</strong>',
  startConversationLabel: 'Konversation beginnen',
  startConversationSub: 'Wir kümmern uns sofort darum.',
  conversationsHeader: 'Ihre Konversationen',
  emptyConversationsTitle: 'Noch keine Konversationen',
  emptyConversationsSub: 'Starten Sie oben eine, dann erscheint sie hier beim nächsten Mal.',
  poweredBy: 'Bereitgestellt von',
  defaultAuthorName: 'Agent',
  roleAi: 'KI',
  roleHuman: 'Mensch',
  timeNow: 'jetzt',
  timeMin: '{n}m',
  timeHour: '{n}h',
  timeDay: '{n}T',
  timeWeek: '{n}W',
  timeMonth: '{n}Mon',
};

export default de;
