import type { Strings } from './types.js';

const en: Strings = {
  launcherAriaLabel: 'Open chat',
  closeAriaLabel: 'Close',
  backAriaLabel: 'Back',
  messageAriaLabel: 'Message',
  sendAriaLabel: 'Send',
  agentTypingAriaLabel: 'Agent is typing',
  newConversation: 'New conversation',
  conversation: 'Conversation',
  onlineNow: 'Online now',
  defaultTeammateName: 'Teammate',
  typicallyReplies: 'typically replies in a few minutes',
  statusReconnecting: 'Reconnecting…',
  statusDisconnected: 'Disconnected.',
  saveThreadEyebrow: 'Save this thread',
  saveThreadBlurb: "Drop an email and we'll keep this conversation around if you close the window.",
  saveThreadCta: 'Save →',
  saveThreadSkip: 'Not now',
  saveThreadDoneEyebrow: '● Saved',
  saveThreadDoneTemplate: "We'll email you at {email} if anything new lands here.",
  emailPlaceholder: 'you@company.com',
  composerPlaceholder: 'Type a message…',
  defaultEyebrow: 'Powered by Munin',
  defaultGreeting: 'Hi there. How can we help?',
  defaultTitle: 'Chat with us',
  welcomeRepliesAboutHtml: 'Replies in about <strong>2 min</strong>',
  startConversationLabel: 'Start a conversation',
  startConversationSub: "We'll get an agent on it right away.",
  conversationsHeader: 'Your conversations',
  emptyConversationsTitle: 'No conversations yet',
  emptyConversationsSub: "Start one above and it'll show up here for next time.",
  poweredBy: 'Powered by',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'human',
  timeNow: 'now',
  timeMin: '{n}m',
  timeHour: '{n}h',
  timeDay: '{n}d',
  timeWeek: '{n}w',
  timeMonth: '{n}mo',
  voiceCallLabel: 'Call',
  voiceStartAriaLabel: 'Start voice call',
  voiceEndAriaLabel: 'End voice call',
  voiceMinimizeAriaLabel: 'Back to chat (keep call running)',
  voiceResumeAriaLabel: 'Return to call',
  voiceConnecting: 'Connecting…',
  voiceLive: 'Live',
  voiceHint: 'Voice runs through this widget — no phone number, no app install.',
  voiceMute: 'Mute',
  voiceMuted: 'Muted',
  voiceEnd: 'End',
  voiceBackToChat: 'Back to chat',
  voiceOnCallWithTemplate: 'On call with {who}',
  voiceTapToReturn: 'Tap to return',
  voiceFailed: 'Voice call failed',
};

export default en;
