import type { Strings } from './types.js';

const es: Strings = {
  launcherAriaLabel: 'Abrir chat',
  closeAriaLabel: 'Cerrar',
  backAriaLabel: 'Atrás',
  messageAriaLabel: 'Mensaje',
  sendAriaLabel: 'Enviar',
  agentTypingAriaLabel: 'El agente está escribiendo',
  newConversation: 'Nueva conversación',
  conversation: 'Conversación',
  onlineNow: 'En línea ahora',
  defaultTeammateName: 'Compañero',
  typicallyReplies: 'normalmente responde en unos minutos',
  statusReconnecting: 'Reconectando…',
  statusDisconnected: 'Desconectado.',
  saveThreadEyebrow: 'Guardar esta conversación',
  saveThreadBlurb: 'Deja tu correo y guardaremos esta conversación si cierras la ventana.',
  saveThreadCta: 'Guardar →',
  saveThreadSkip: 'Ahora no',
  saveThreadDoneEyebrow: '● Guardado',
  saveThreadDoneTemplate: 'Te escribiremos a {email} si pasa algo nuevo aquí.',
  emailPlaceholder: 'tu@empresa.es',
  composerPlaceholder: 'Escribe un mensaje…',
  defaultEyebrow: 'Con la tecnología de Munin',
  defaultGreeting: 'Hola. ¿En qué podemos ayudarte?',
  defaultTitle: 'Chatea con nosotros',
  welcomeRepliesAboutHtml: 'Respuesta en aproximadamente <strong>2 min</strong>',
  startConversationLabel: 'Iniciar una conversación',
  startConversationSub: 'Asignaremos un agente enseguida.',
  conversationsHeader: 'Tus conversaciones',
  emptyConversationsTitle: 'Aún no hay conversaciones',
  emptyConversationsSub: 'Inicia una arriba y aparecerá aquí la próxima vez.',
  poweredBy: 'Con la tecnología de',
  defaultAuthorName: 'Agente',
  roleAi: 'IA',
  roleHuman: 'humano',
  timeNow: 'ahora',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} d',
  timeWeek: '{n} sem',
  timeMonth: '{n} mes',
};

export default es;
