import type { Strings } from './types.ts';

const et: Strings = {
  launcherAriaLabel: 'Ava vestlus',
  closeAriaLabel: 'Sulge',
  backAriaLabel: 'Tagasi',
  messageAriaLabel: 'Sõnum',
  sendAriaLabel: 'Saada',
  agentTypingAriaLabel: 'Agent kirjutab',
  newConversation: 'Uus vestlus',
  conversation: 'Vestlus',
  onlineNow: 'Praegu võrgus',
  defaultTeammateName: 'Tiimikaaslane',
  typicallyReplies: 'vastab tavaliselt mõne minutiga',
  statusReconnecting: 'Ühendan uuesti…',
  statusDisconnected: 'Ühendus katkes.',
  saveThreadEyebrow: 'Salvesta see vestlus',
  saveThreadBlurb: 'Jäta oma e-posti aadress, siis hoiame vestluse alles, kui sa akna sulged.',
  saveThreadCta: 'Salvesta →',
  saveThreadSkip: 'Mitte praegu',
  saveThreadDoneEyebrow: '● Salvestatud',
  saveThreadDoneTemplate: 'Kirjutame sulle aadressil {email}, kui siia midagi uut lisandub.',
  emailPlaceholder: 'sina@ettevote.ee',
  composerPlaceholder: 'Kirjuta sõnum…',
  defaultEyebrow: 'Töötab platvormil Munin',
  defaultGreeting: 'Tere. Kuidas saame aidata?',
  defaultTitle: 'Vestle meiega',
  welcomeRepliesAboutHtml: 'Vastus umbes <strong>2 min</strong>',
  startConversationLabel: 'Alusta vestlust',
  startConversationSub: 'Anname selle kohe agendile.',
  conversationsHeader: 'Sinu vestlused',
  emptyConversationsTitle: 'Vestlusi veel ei ole',
  emptyConversationsSub: 'Alusta üleval üht, siis ilmub see järgmine kord siia.',
  poweredBy: 'Töötab platvormil',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'inimene',
  timeNow: 'nüüd',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} p',
  timeWeek: '{n} n',
  timeMonth: '{n} k',
  voiceCallLabel: 'Helista',
  voiceStartAriaLabel: 'Alusta kõnet',
  voiceEndAriaLabel: 'Lõpeta kõne',
  voiceMinimizeAriaLabel: 'Tagasi vestlusesse (jäta kõne käima)',
  voiceResumeAriaLabel: 'Tagasi kõne juurde',
  voiceConnecting: 'Ühendan…',
  voiceLive: 'Otse',
  voiceHint: 'Kõne käib selle vidina kaudu — telefoninumbrit ega rakendust pole vaja.',
  voiceMute: 'Vaigista',
  voiceMuted: 'Vaigistatud',
  voiceEnd: 'Lõpeta',
  voiceBackToChat: 'Tagasi vestlusesse',
  voiceOnCallWithTemplate: 'Kõne: {who}',
  voiceTapToReturn: 'Puuduta naasmiseks',
  voiceFailed: 'Kõne ebaõnnestus',
  productViewLabel: 'Vaata',
};

export default et;
