import type { Strings } from './types.ts';

const fi: Strings = {
  launcherAriaLabel: 'Avaa chat',
  closeAriaLabel: 'Sulje',
  backAriaLabel: 'Takaisin',
  messageAriaLabel: 'Viesti',
  sendAriaLabel: 'Lähetä',
  agentTypingAriaLabel: 'Agentti kirjoittaa',
  newConversation: 'Uusi keskustelu',
  conversation: 'Keskustelu',
  onlineNow: 'Paikalla nyt',
  defaultTeammateName: 'Tiimin jäsen',
  typicallyReplies: 'vastaa yleensä muutamassa minuutissa',
  statusReconnecting: 'Yhdistetään uudelleen…',
  statusDisconnected: 'Yhteys katkennut.',
  saveThreadEyebrow: 'Tallenna tämä keskustelu',
  saveThreadBlurb: 'Jätä sähköposti, niin tallennamme keskustelun, jos suljet ikkunan.',
  saveThreadCta: 'Tallenna →',
  saveThreadSkip: 'Ei nyt',
  saveThreadDoneEyebrow: '● Tallennettu',
  saveThreadDoneTemplate: 'Lähetämme sähköpostia osoitteeseen {email}, jos täällä tapahtuu jotain uutta.',
  emailPlaceholder: 'sina@yritys.fi',
  composerPlaceholder: 'Kirjoita viesti…',
  defaultEyebrow: 'Toimittaa Munin',
  defaultGreeting: 'Hei. Miten voimme auttaa?',
  defaultTitle: 'Keskustele kanssamme',
  welcomeRepliesInstantly: 'Vastaa heti',
  startConversationLabel: 'Aloita keskustelu',
  startConversationSub: 'Laitamme agentin asialle heti.',
  conversationsHeader: 'Keskustelusi',
  emptyConversationsTitle: 'Ei keskusteluja vielä',
  emptyConversationsSub: 'Aloita yllä, niin se näkyy täällä ensi kerralla.',
  poweredBy: 'Toimittaa',
  defaultAuthorName: 'Agentti',
  roleAi: 'AI',
  roleHuman: 'ihminen',
  timeNow: 'nyt',
  timeMin: '{n}min',
  timeHour: '{n}t',
  timeDay: '{n}p',
  timeWeek: '{n}vk',
  timeMonth: '{n}kk',
  voiceCallLabel: 'Soita',
  voiceStartAriaLabel: 'Aloita äänipuhelu',
  voiceEndAriaLabel: 'Lopeta äänipuhelu',
  voiceMinimizeAriaLabel: 'Takaisin chatiin (jätä puhelu päälle)',
  voiceResumeAriaLabel: 'Takaisin puheluun',
  voiceConnecting: 'Yhdistetään…',
  voiceLive: 'Käynnissä',
  voiceHint: 'Ääni kulkee tämän widgetin kautta — ei puhelinnumeroa, ei sovellusta.',
  voiceMute: 'Mykistä',
  voiceMuted: 'Mykistetty',
  voiceEnd: 'Lopeta',
  voiceBackToChat: 'Takaisin chatiin',
  voiceOnCallWithTemplate: 'Puhelussa: {who}',
  voiceTapToReturn: 'Palaa napauttamalla',
  voiceFailed: 'Äänipuhelu epäonnistui',
  productViewLabel: 'Katso',
  attachAriaLabel: 'Liitä kuva',
  attachDropHint: 'Pudota kuva tähän',
  attachUploading: 'Lähetetään…',
  attachFailed: 'Kuvan lähetys ei onnistunut. Yritä uudelleen.',
  attachRemoveAriaLabel: 'Poista kuva',
  attachTooMany: 'Voit liittää enintään {n} kuvaa.',
  attachTypeRejected: 'Otamme vastaan PNG-, JPEG-, GIF- ja WebP-kuvia.',
  attachTooLarge: 'Kuvan koko saa olla enintään {n} MB.',
  attachmentUnavailable: 'Kuva ei ole enää saatavilla',
  lightboxCloseAriaLabel: 'Sulje kuva',
};

export default fi;
