import type { Strings } from './types.js';

const fr: Strings = {
  launcherAriaLabel: 'Ouvrir le chat',
  closeAriaLabel: 'Fermer',
  backAriaLabel: 'Retour',
  messageAriaLabel: 'Message',
  sendAriaLabel: 'Envoyer',
  agentTypingAriaLabel: "L'agent écrit",
  newConversation: 'Nouvelle conversation',
  conversation: 'Conversation',
  onlineNow: 'En ligne',
  defaultTeammateName: 'Coéquipier',
  typicallyReplies: 'répond généralement en quelques minutes',
  statusReconnecting: 'Reconnexion…',
  statusDisconnected: 'Déconnecté.',
  saveThreadEyebrow: 'Sauvegarder cette conversation',
  saveThreadBlurb: 'Laissez votre e-mail et nous conserverons cette conversation si vous fermez la fenêtre.',
  saveThreadCta: 'Enregistrer →',
  saveThreadSkip: 'Plus tard',
  saveThreadDoneEyebrow: '● Enregistré',
  saveThreadDoneTemplate: 'Nous vous écrirons à {email} si du nouveau arrive ici.',
  emailPlaceholder: 'vous@entreprise.fr',
  composerPlaceholder: 'Écrire un message…',
  defaultEyebrow: 'Propulsé par Munin',
  defaultGreeting: 'Bonjour. Comment pouvons-nous vous aider ?',
  defaultTitle: 'Discutez avec nous',
  welcomeRepliesAboutHtml: 'Réponse en environ <strong>2 min</strong>',
  startConversationLabel: 'Démarrer une conversation',
  startConversationSub: 'Nous mobilisons un agent tout de suite.',
  conversationsHeader: 'Vos conversations',
  emptyConversationsTitle: 'Aucune conversation pour le moment',
  emptyConversationsSub: 'Démarrez-en une au-dessus, elle apparaîtra ici la prochaine fois.',
  poweredBy: 'Propulsé par',
  defaultAuthorName: 'Agent',
  roleAi: 'IA',
  roleHuman: 'humain',
  timeNow: 'maintenant',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} j',
  timeWeek: '{n} sem',
  timeMonth: '{n} mois',
  voiceCallLabel: 'Appeler',
  voiceStartAriaLabel: "Démarrer l'appel vocal",
  voiceEndAriaLabel: "Terminer l'appel vocal",
  voiceMinimizeAriaLabel: "Retour au chat (l'appel continue)",
  voiceResumeAriaLabel: "Revenir à l'appel",
  voiceConnecting: 'Connexion…',
  voiceLive: 'En direct',
  voiceHint: 'La voix passe par ce widget — aucun numéro, aucune appli.',
  voiceMute: 'Couper',
  voiceMuted: 'Coupé',
  voiceEnd: 'Terminer',
  voiceBackToChat: 'Retour au chat',
  voiceOnCallWithTemplate: 'En appel avec {who}',
  voiceTapToReturn: 'Touchez pour revenir',
  voiceFailed: "L'appel vocal a échoué",
};

export default fr;
