import type { Strings } from './types.ts';

const hu: Strings = {
  launcherAriaLabel: 'Csevegés megnyitása',
  closeAriaLabel: 'Bezárás',
  backAriaLabel: 'Vissza',
  messageAriaLabel: 'Üzenet',
  sendAriaLabel: 'Küldés',
  agentTypingAriaLabel: 'Az ügyintéző ír',
  newConversation: 'Új beszélgetés',
  conversation: 'Beszélgetés',
  onlineNow: 'Most online',
  defaultTeammateName: 'Csapattag',
  typicallyReplies: 'általában néhány percen belül válaszol',
  statusReconnecting: 'Újrakapcsolódás…',
  statusDisconnected: 'A kapcsolat megszakadt.',
  saveThreadEyebrow: 'Beszélgetés mentése',
  saveThreadBlurb: 'Adja meg az e-mail-címét, és megőrizzük a beszélgetést, ha bezárja az ablakot.',
  saveThreadCta: 'Mentés →',
  saveThreadSkip: 'Most nem',
  saveThreadDoneEyebrow: '● Mentve',
  saveThreadDoneTemplate: 'Írunk a {email} címre, ha itt új üzenet érkezik.',
  emailPlaceholder: 'on@ceg.hu',
  composerPlaceholder: 'Írjon egy üzenetet…',
  defaultEyebrow: 'Működteti: Munin',
  defaultGreeting: 'Üdv. Miben segíthetünk?',
  defaultTitle: 'Írjon nekünk',
  welcomeRepliesAboutHtml: 'Válasz kb. <strong>2 perc</strong>',
  startConversationLabel: 'Beszélgetés indítása',
  startConversationSub: 'Azonnal ügyintézőt állítunk rá.',
  conversationsHeader: 'Az Ön beszélgetései',
  emptyConversationsTitle: 'Még nincs beszélgetés',
  emptyConversationsSub: 'Indítson egyet fent, és legközelebb itt találja.',
  poweredBy: 'Működteti:',
  defaultAuthorName: 'Ügyintéző',
  roleAi: 'AI',
  roleHuman: 'ember',
  timeNow: 'most',
  timeMin: '{n} p',
  timeHour: '{n} ó',
  timeDay: '{n} n',
  timeWeek: '{n} hét',
  timeMonth: '{n} hó',
  voiceCallLabel: 'Hívás',
  voiceStartAriaLabel: 'Hanghívás indítása',
  voiceEndAriaLabel: 'Hanghívás befejezése',
  voiceMinimizeAriaLabel: 'Vissza a csevegéshez (a hívás tovább fut)',
  voiceResumeAriaLabel: 'Vissza a híváshoz',
  voiceConnecting: 'Kapcsolódás…',
  voiceLive: 'Élő',
  voiceHint: 'A hang ezen a widgeten megy — nem kell se telefonszám, se alkalmazás.',
  voiceMute: 'Némítás',
  voiceMuted: 'Némítva',
  voiceEnd: 'Befejezés',
  voiceBackToChat: 'Vissza a csevegéshez',
  voiceOnCallWithTemplate: 'Hívás: {who}',
  voiceTapToReturn: 'Koppintson a visszatéréshez',
  voiceFailed: 'A hanghívás nem sikerült',
  productViewLabel: 'Megnézem',
};

export default hu;
