import type { Strings } from './types.js';

const is: Strings = {
  launcherAriaLabel: 'Opna spjall',
  closeAriaLabel: 'Loka',
  backAriaLabel: 'Til baka',
  messageAriaLabel: 'Skilaboð',
  sendAriaLabel: 'Senda',
  agentTypingAriaLabel: 'Umboðsmaður er að skrifa',
  newConversation: 'Nýtt samtal',
  conversation: 'Samtal',
  onlineNow: 'Á netinu núna',
  defaultTeammateName: 'Liðsmaður',
  typicallyReplies: 'svarar yfirleitt á nokkrum mínútum',
  statusReconnecting: 'Tengist aftur…',
  statusDisconnected: 'Aftengt.',
  saveThreadEyebrow: 'Vista þetta samtal',
  saveThreadBlurb: 'Skildu eftir netfang og við geymum samtalið ef þú lokar glugganum.',
  saveThreadCta: 'Vista →',
  saveThreadSkip: 'Ekki núna',
  saveThreadDoneEyebrow: '● Vistað',
  saveThreadDoneTemplate: 'Við sendum þér tölvupóst á {email} ef eitthvað nýtt gerist hér.',
  emailPlaceholder: 'thu@fyrirtaeki.is',
  composerPlaceholder: 'Skrifaðu skilaboð…',
  defaultEyebrow: 'Knúið af Munin',
  defaultGreeting: 'Halló. Hvernig getum við hjálpað?',
  defaultTitle: 'Spjallaðu við okkur',
  welcomeRepliesAboutHtml: 'Svar á u.þ.b. <strong>2 mín</strong>',
  startConversationLabel: 'Byrja samtal',
  startConversationSub: 'Við setjum umboðsmann á það strax.',
  conversationsHeader: 'Samtölin þín',
  emptyConversationsTitle: 'Engin samtöl enn',
  emptyConversationsSub: 'Byrjaðu eitt að ofan og það birtist hér næst.',
  poweredBy: 'Knúið af',
  defaultAuthorName: 'Umboðsmaður',
  roleAi: 'gervigreind',
  roleHuman: 'manneskja',
  timeNow: 'núna',
  timeMin: '{n}mín',
  timeHour: '{n}klst',
  timeDay: '{n}d',
  timeWeek: '{n}v',
  timeMonth: '{n}mán',
  voiceCallLabel: 'Hringja',
  voiceStartAriaLabel: 'Hefja talsímtal',
  voiceEndAriaLabel: 'Slíta talsímtali',
  voiceMinimizeAriaLabel: 'Til baka í spjall (halda símtali áfram)',
  voiceResumeAriaLabel: 'Til baka í símtalið',
  voiceConnecting: 'Tengist…',
  voiceLive: 'Í gangi',
  voiceHint: 'Talið fer í gegnum þessa græju — ekkert símanúmer, ekkert forrit.',
  voiceMute: 'Þagga',
  voiceMuted: 'Þaggað',
  voiceEnd: 'Slíta',
  voiceBackToChat: 'Til baka í spjall',
  voiceOnCallWithTemplate: 'Í símtali við {who}',
  voiceTapToReturn: 'Pikkaðu til að snúa aftur',
  voiceFailed: 'Talsímtal mistókst',
};

export default is;
