import type { Strings } from './types.ts';

const it: Strings = {
  launcherAriaLabel: 'Apri chat',
  closeAriaLabel: 'Chiudi',
  backAriaLabel: 'Indietro',
  messageAriaLabel: 'Messaggio',
  sendAriaLabel: 'Invia',
  agentTypingAriaLabel: "L'agente sta scrivendo",
  newConversation: 'Nuova conversazione',
  conversation: 'Conversazione',
  onlineNow: 'Online ora',
  defaultTeammateName: 'Membro del team',
  typicallyReplies: 'di solito risponde in pochi minuti',
  statusReconnecting: 'Riconnessione in corso…',
  statusDisconnected: 'Disconnesso.',
  saveThreadEyebrow: 'Salva questa conversazione',
  saveThreadBlurb: 'Lascia la tua email e conserveremo questa conversazione se chiudi la finestra.',
  saveThreadCta: 'Salva →',
  saveThreadSkip: 'Non ora',
  saveThreadDoneEyebrow: '● Salvato',
  saveThreadDoneTemplate: 'Ti scriveremo a {email} se ci saranno novità qui.',
  emailPlaceholder: 'tu@azienda.it',
  composerPlaceholder: 'Scrivi un messaggio…',
  defaultEyebrow: 'Con tecnologia Munin',
  defaultGreeting: 'Ciao. Come possiamo aiutarti?',
  defaultTitle: 'Chatta con noi',
  welcomeRepliesAboutHtml: 'Risposta in circa <strong>2 min</strong>',
  startConversationLabel: 'Inizia una conversazione',
  startConversationSub: 'Assegniamo un agente subito.',
  conversationsHeader: 'Le tue conversazioni',
  emptyConversationsTitle: 'Nessuna conversazione',
  emptyConversationsSub: 'Inizia sopra e apparirà qui la prossima volta.',
  poweredBy: 'Con tecnologia',
  defaultAuthorName: 'Agente',
  roleAi: 'IA',
  roleHuman: 'umano',
  timeNow: 'ora',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} g',
  timeWeek: '{n} sett',
  timeMonth: '{n} mese',
  voiceCallLabel: 'Chiama',
  voiceStartAriaLabel: 'Avvia chiamata vocale',
  voiceEndAriaLabel: 'Termina chiamata vocale',
  voiceMinimizeAriaLabel: 'Torna alla chat (mantieni la chiamata attiva)',
  voiceResumeAriaLabel: 'Torna alla chiamata',
  voiceConnecting: 'Connessione…',
  voiceLive: 'In diretta',
  voiceHint: 'La voce passa per questo widget — nessun numero, nessuna app.',
  voiceMute: 'Muto',
  voiceMuted: 'Mutato',
  voiceEnd: 'Termina',
  voiceBackToChat: 'Torna alla chat',
  voiceOnCallWithTemplate: 'In chiamata con {who}',
  voiceTapToReturn: 'Tocca per tornare',
  voiceFailed: 'Chiamata vocale fallita',
};

export default it;
