import type { Strings } from './types.ts';

const lt: Strings = {
  launcherAriaLabel: 'Atidaryti pokalbį',
  closeAriaLabel: 'Užverti',
  backAriaLabel: 'Atgal',
  messageAriaLabel: 'Pranešimas',
  sendAriaLabel: 'Siųsti',
  agentTypingAriaLabel: 'Agentas rašo',
  newConversation: 'Naujas pokalbis',
  conversation: 'Pokalbis',
  onlineNow: 'Šiuo metu prisijungęs',
  defaultTeammateName: 'Komandos narys',
  typicallyReplies: 'paprastai atsako per kelias minutes',
  statusReconnecting: 'Bandoma prisijungti…',
  statusDisconnected: 'Atsijungta.',
  saveThreadEyebrow: 'Išsaugoti šį pokalbį',
  saveThreadBlurb: 'Palikite el. paštą ir pokalbį išsaugosime, net jei uždarysite langą.',
  saveThreadCta: 'Išsaugoti →',
  saveThreadSkip: 'Ne dabar',
  saveThreadDoneEyebrow: '● Išsaugota',
  saveThreadDoneTemplate: 'Parašysime jums adresu {email}, jei čia atsiras kas nors nauja.',
  emailPlaceholder: 'jus@imone.lt',
  composerPlaceholder: 'Rašykite pranešimą…',
  defaultEyebrow: 'Veikia su Munin',
  defaultGreeting: 'Sveiki. Kaip galime padėti?',
  defaultTitle: 'Rašykite mums',
  welcomeRepliesAboutHtml: 'Atsakymas maždaug per <strong>2 min</strong>',
  startConversationLabel: 'Pradėti pokalbį',
  startConversationSub: 'Iškart perduosime agentui.',
  conversationsHeader: 'Jūsų pokalbiai',
  emptyConversationsTitle: 'Pokalbių dar nėra',
  emptyConversationsSub: 'Pradėkite pokalbį viršuje ir kitą kartą jis bus čia.',
  poweredBy: 'Veikia su',
  defaultAuthorName: 'Agentas',
  roleAi: 'AI',
  roleHuman: 'žmogus',
  timeNow: 'dabar',
  timeMin: '{n} min',
  timeHour: '{n} val',
  timeDay: '{n} d',
  timeWeek: '{n} sav',
  timeMonth: '{n} mėn',
  voiceCallLabel: 'Skambinti',
  voiceStartAriaLabel: 'Pradėti balso skambutį',
  voiceEndAriaLabel: 'Baigti balso skambutį',
  voiceMinimizeAriaLabel: 'Atgal į pokalbį (skambutis tęsiasi)',
  voiceResumeAriaLabel: 'Grįžti į skambutį',
  voiceConnecting: 'Sujungiama…',
  voiceLive: 'Tiesiogiai',
  voiceHint: 'Balsas veikia per šį valdiklį — nereikia nei telefono numerio, nei programėlės.',
  voiceMute: 'Nutildyti',
  voiceMuted: 'Nutildyta',
  voiceEnd: 'Baigti',
  voiceBackToChat: 'Atgal į pokalbį',
  voiceOnCallWithTemplate: 'Skambutis: {who}',
  voiceTapToReturn: 'Palieskite, kad grįžtumėte',
  voiceFailed: 'Balso skambutis nepavyko',
  productViewLabel: 'Žiūrėti',
};

export default lt;
