import type { Strings } from './types.ts';

const lv: Strings = {
  launcherAriaLabel: 'Atvērt tērzēšanu',
  closeAriaLabel: 'Aizvērt',
  backAriaLabel: 'Atpakaļ',
  messageAriaLabel: 'Ziņa',
  sendAriaLabel: 'Sūtīt',
  agentTypingAriaLabel: 'Aģents raksta',
  newConversation: 'Jauna saruna',
  conversation: 'Saruna',
  onlineNow: 'Tiešsaistē',
  defaultTeammateName: 'Komandas biedrs',
  typicallyReplies: 'parasti atbild dažu minūšu laikā',
  statusReconnecting: 'Atjauno savienojumu…',
  statusDisconnected: 'Savienojums pārtrūka.',
  saveThreadEyebrow: 'Saglabāt šo sarunu',
  saveThreadBlurb: 'Atstājiet e-pasta adresi, un saruna saglabāsies arī tad, ja aizvērsiet logu.',
  saveThreadCta: 'Saglabāt →',
  saveThreadSkip: 'Ne tagad',
  saveThreadDoneEyebrow: '● Saglabāts',
  saveThreadDoneTemplate: 'Rakstīsim uz {email}, ja šeit parādīsies kaut kas jauns.',
  emailPlaceholder: 'jus@uznemums.lv',
  composerPlaceholder: 'Rakstiet ziņu…',
  defaultEyebrow: 'Nodrošina Munin',
  defaultGreeting: 'Sveiki. Kā varam palīdzēt?',
  defaultTitle: 'Tērzējiet ar mums',
  welcomeRepliesAboutHtml: 'Atbilde apmēram <strong>2 min</strong>',
  startConversationLabel: 'Sākt sarunu',
  startConversationSub: 'Uzreiz nodosim to aģentam.',
  conversationsHeader: 'Jūsu sarunas',
  emptyConversationsTitle: 'Vēl nav sarunu',
  emptyConversationsSub: 'Sāciet sarunu augšpusē, un nākamreiz tā būs redzama šeit.',
  poweredBy: 'Nodrošina',
  defaultAuthorName: 'Aģents',
  roleAi: 'AI',
  roleHuman: 'cilvēks',
  timeNow: 'tagad',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} d',
  timeWeek: '{n} ned',
  timeMonth: '{n} mēn',
  voiceCallLabel: 'Zvanīt',
  voiceStartAriaLabel: 'Sākt balss zvanu',
  voiceEndAriaLabel: 'Beigt balss zvanu',
  voiceMinimizeAriaLabel: 'Atpakaļ uz tērzēšanu (zvans paliek aktīvs)',
  voiceResumeAriaLabel: 'Atgriezties zvanā',
  voiceConnecting: 'Savienojas…',
  voiceLive: 'Tiešraidē',
  voiceHint: 'Balss darbojas caur šo logrīku — nav vajadzīgs ne telefona numurs, ne lietotne.',
  voiceMute: 'Izslēgt skaņu',
  voiceMuted: 'Skaņa izslēgta',
  voiceEnd: 'Beigt',
  voiceBackToChat: 'Atpakaļ uz tērzēšanu',
  voiceOnCallWithTemplate: 'Saruna: {who}',
  voiceTapToReturn: 'Pieskarieties, lai atgrieztos',
  voiceFailed: 'Balss zvans neizdevās',
  productViewLabel: 'Skatīt',
};

export default lv;
