import type { Strings } from './types.js';

const nb: Strings = {
  launcherAriaLabel: 'Åpne chat',
  closeAriaLabel: 'Lukk',
  backAriaLabel: 'Tilbake',
  messageAriaLabel: 'Melding',
  sendAriaLabel: 'Send',
  agentTypingAriaLabel: 'Agenten skriver',
  newConversation: 'Ny samtale',
  conversation: 'Samtale',
  onlineNow: 'På nett nå',
  defaultTeammateName: 'Teammedlem',
  typicallyReplies: 'svarer vanligvis på noen minutter',
  statusReconnecting: 'Kobler til igjen…',
  statusDisconnected: 'Frakoblet.',
  saveThreadEyebrow: 'Lagre denne samtalen',
  saveThreadBlurb: 'Skriv e-posten din, så tar vi vare på samtalen om du lukker vinduet.',
  saveThreadCta: 'Lagre →',
  saveThreadSkip: 'Ikke nå',
  saveThreadDoneEyebrow: '● Lagret',
  saveThreadDoneTemplate: 'Vi sender deg en e-post på {email} om noe nytt dukker opp her.',
  emailPlaceholder: 'du@firma.no',
  composerPlaceholder: 'Skriv en melding…',
  defaultEyebrow: 'Drevet av Munin',
  defaultGreeting: 'Hei. Hva kan vi hjelpe deg med?',
  defaultTitle: 'Chat med oss',
  welcomeRepliesAboutHtml: 'Svar på omtrent <strong>2 min</strong>',
  startConversationLabel: 'Start en samtale',
  startConversationSub: 'Vi setter en agent på saken med en gang.',
  conversationsHeader: 'Dine samtaler',
  emptyConversationsTitle: 'Ingen samtaler ennå',
  emptyConversationsSub: 'Start en over, så dukker den opp her neste gang.',
  poweredBy: 'Drevet av',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'menneske',
  timeNow: 'nå',
  timeMin: '{n}m',
  timeHour: '{n}t',
  timeDay: '{n}d',
  timeWeek: '{n}u',
  timeMonth: '{n}mnd',
};

export default nb;
