import type { Strings } from './types.ts';

const nl: Strings = {
  launcherAriaLabel: 'Chat openen',
  closeAriaLabel: 'Sluiten',
  backAriaLabel: 'Terug',
  messageAriaLabel: 'Bericht',
  sendAriaLabel: 'Verzenden',
  agentTypingAriaLabel: 'Agent is aan het typen',
  newConversation: 'Nieuw gesprek',
  conversation: 'Gesprek',
  onlineNow: 'Nu online',
  defaultTeammateName: 'Teamlid',
  typicallyReplies: 'reageert meestal binnen enkele minuten',
  statusReconnecting: 'Opnieuw verbinden…',
  statusDisconnected: 'Verbinding verbroken.',
  saveThreadEyebrow: 'Dit gesprek bewaren',
  saveThreadBlurb: 'Laat je e-mail achter, dan bewaren we dit gesprek als je het venster sluit.',
  saveThreadCta: 'Bewaren →',
  saveThreadSkip: 'Niet nu',
  saveThreadDoneEyebrow: '● Bewaard',
  saveThreadDoneTemplate: 'We e-mailen je op {email} als hier iets nieuws gebeurt.',
  emailPlaceholder: 'jij@bedrijf.nl',
  composerPlaceholder: 'Typ een bericht…',
  defaultEyebrow: 'Aangedreven door Munin',
  defaultGreeting: 'Hallo. Hoe kunnen we helpen?',
  defaultTitle: 'Chat met ons',
  welcomeRepliesAboutHtml: 'Antwoord in ongeveer <strong>2 min</strong>',
  startConversationLabel: 'Start een gesprek',
  startConversationSub: 'We zetten direct een agent op de zaak.',
  conversationsHeader: 'Jouw gesprekken',
  emptyConversationsTitle: 'Nog geen gesprekken',
  emptyConversationsSub: 'Start er een hierboven, dan staat hij hier de volgende keer.',
  poweredBy: 'Aangedreven door',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'mens',
  timeNow: 'nu',
  timeMin: '{n}m',
  timeHour: '{n}u',
  timeDay: '{n}d',
  timeWeek: '{n}w',
  timeMonth: '{n}mnd',
  voiceCallLabel: 'Bellen',
  voiceStartAriaLabel: 'Spraakoproep starten',
  voiceEndAriaLabel: 'Spraakoproep beëindigen',
  voiceMinimizeAriaLabel: 'Terug naar chat (oproep blijft actief)',
  voiceResumeAriaLabel: 'Terug naar de oproep',
  voiceConnecting: 'Verbinden…',
  voiceLive: 'Live',
  voiceHint: 'Stem loopt via deze widget — geen telefoonnummer, geen app.',
  voiceMute: 'Dempen',
  voiceMuted: 'Gedempt',
  voiceEnd: 'Beëindigen',
  voiceBackToChat: 'Terug naar chat',
  voiceOnCallWithTemplate: 'In gesprek met {who}',
  voiceTapToReturn: 'Tik om terug te keren',
  voiceFailed: 'Spraakoproep mislukt',
};

export default nl;
