import type { Strings } from './types.ts';

const nn: Strings = {
  launcherAriaLabel: 'Opne chat',
  closeAriaLabel: 'Lukk',
  backAriaLabel: 'Tilbake',
  messageAriaLabel: 'Melding',
  sendAriaLabel: 'Send',
  agentTypingAriaLabel: 'Agenten skriv',
  newConversation: 'Ny samtale',
  conversation: 'Samtale',
  onlineNow: 'På nett no',
  defaultTeammateName: 'Teammedlem',
  typicallyReplies: 'svarar vanlegvis på nokre minutt',
  statusReconnecting: 'Koplar til igjen…',
  statusDisconnected: 'Fråkopla.',
  saveThreadEyebrow: 'Lagre denne samtalen',
  saveThreadBlurb: 'Skriv e-posten din, så tek vi vare på samtalen om du lukkar vindauget.',
  saveThreadCta: 'Lagre →',
  saveThreadSkip: 'Ikkje no',
  saveThreadDoneEyebrow: '● Lagra',
  saveThreadDoneTemplate: 'Vi sender deg ein e-post på {email} om noko nytt dukkar opp her.',
  emailPlaceholder: 'du@firma.no',
  composerPlaceholder: 'Skriv ei melding…',
  defaultEyebrow: 'Driven av Munin',
  defaultGreeting: 'Hei. Kva kan vi hjelpe deg med?',
  defaultTitle: 'Chat med oss',
  welcomeRepliesAboutHtml: 'Svar på omtrent <strong>2 min</strong>',
  startConversationLabel: 'Start ein samtale',
  startConversationSub: 'Vi set ein agent på saka med ein gong.',
  conversationsHeader: 'Dine samtalar',
  emptyConversationsTitle: 'Ingen samtalar enno',
  emptyConversationsSub: 'Start ein over, så dukkar han opp her neste gong.',
  poweredBy: 'Driven av',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'menneske',
  timeNow: 'no',
  timeMin: '{n}m',
  timeHour: '{n}t',
  timeDay: '{n}d',
  timeWeek: '{n}v',
  timeMonth: '{n}mnd',
  voiceCallLabel: 'Ring',
  voiceStartAriaLabel: 'Start taleanrop',
  voiceEndAriaLabel: 'Avslutt taleanrop',
  voiceMinimizeAriaLabel: 'Tilbake til chat (hald anropet aktivt)',
  voiceResumeAriaLabel: 'Tilbake til anropet',
  voiceConnecting: 'Koplar til…',
  voiceLive: 'Live',
  voiceHint: 'Tale går gjennom denne widgeten — ingen telefonnummer, ingen app.',
  voiceMute: 'Demp',
  voiceMuted: 'Dempa',
  voiceEnd: 'Avslutt',
  voiceBackToChat: 'Tilbake til chat',
  voiceOnCallWithTemplate: 'I anrop med {who}',
  voiceTapToReturn: 'Trykk for å gå tilbake',
  voiceFailed: 'Taleanropet mislukka',
  productViewLabel: 'Sjå',
};

export default nn;
