import type { Strings } from './types.ts';

const pl: Strings = {
  launcherAriaLabel: 'Otwórz czat',
  closeAriaLabel: 'Zamknij',
  backAriaLabel: 'Wstecz',
  messageAriaLabel: 'Wiadomość',
  sendAriaLabel: 'Wyślij',
  agentTypingAriaLabel: 'Agent pisze',
  newConversation: 'Nowa rozmowa',
  conversation: 'Rozmowa',
  onlineNow: 'Teraz online',
  defaultTeammateName: 'Członek zespołu',
  typicallyReplies: 'zwykle odpowiada w ciągu kilku minut',
  statusReconnecting: 'Łączenie ponowne…',
  statusDisconnected: 'Rozłączono.',
  saveThreadEyebrow: 'Zapisz tę rozmowę',
  saveThreadBlurb: 'Zostaw e-mail, a zachowamy tę rozmowę, jeśli zamkniesz okno.',
  saveThreadCta: 'Zapisz →',
  saveThreadSkip: 'Nie teraz',
  saveThreadDoneEyebrow: '● Zapisano',
  saveThreadDoneTemplate: 'Napiszemy do Ciebie na {email}, jeśli pojawi się tu coś nowego.',
  emailPlaceholder: 'ty@firma.pl',
  composerPlaceholder: 'Napisz wiadomość…',
  defaultEyebrow: 'Napędzane przez Munin',
  defaultGreeting: 'Cześć. W czym możemy pomóc?',
  defaultTitle: 'Porozmawiaj z nami',
  welcomeRepliesAboutHtml: 'Odpowiedź w ok. <strong>2 min</strong>',
  startConversationLabel: 'Rozpocznij rozmowę',
  startConversationSub: 'Zaraz weźmie się za to agent.',
  conversationsHeader: 'Twoje rozmowy',
  emptyConversationsTitle: 'Nie ma jeszcze rozmów',
  emptyConversationsSub: 'Rozpocznij rozmowę powyżej, pojawi się tutaj następnym razem.',
  poweredBy: 'Napędzane przez',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'człowiek',
  timeNow: 'teraz',
  timeMin: '{n} min',
  timeHour: '{n} godz',
  timeDay: '{n} dn',
  timeWeek: '{n} tyg',
  timeMonth: '{n} mies',
  voiceCallLabel: 'Zadzwoń',
  voiceStartAriaLabel: 'Rozpocznij rozmowę głosową',
  voiceEndAriaLabel: 'Zakończ rozmowę głosową',
  voiceMinimizeAriaLabel: 'Wróć do czatu (zachowaj rozmowę aktywną)',
  voiceResumeAriaLabel: 'Wróć do rozmowy',
  voiceConnecting: 'Łączenie…',
  voiceLive: 'Na żywo',
  voiceHint: 'Głos idzie przez ten widget — bez numeru telefonu, bez aplikacji.',
  voiceMute: 'Wycisz',
  voiceMuted: 'Wyciszono',
  voiceEnd: 'Zakończ',
  voiceBackToChat: 'Wróć do czatu',
  voiceOnCallWithTemplate: 'Rozmowa z {who}',
  voiceTapToReturn: 'Dotknij, aby wrócić',
  voiceFailed: 'Rozmowa głosowa nieudana',
};

export default pl;
