import type { Strings } from './types.ts';

const pt: Strings = {
  launcherAriaLabel: 'Abrir chat',
  closeAriaLabel: 'Fechar',
  backAriaLabel: 'Voltar',
  messageAriaLabel: 'Mensagem',
  sendAriaLabel: 'Enviar',
  agentTypingAriaLabel: 'O agente está a escrever',
  newConversation: 'Nova conversa',
  conversation: 'Conversa',
  onlineNow: 'Online agora',
  defaultTeammateName: 'Membro da equipa',
  typicallyReplies: 'costuma responder em poucos minutos',
  statusReconnecting: 'A reconectar…',
  statusDisconnected: 'Desligado.',
  saveThreadEyebrow: 'Guardar esta conversa',
  saveThreadBlurb: 'Deixa o teu e-mail e guardamos esta conversa se fechares a janela.',
  saveThreadCta: 'Guardar →',
  saveThreadSkip: 'Agora não',
  saveThreadDoneEyebrow: '● Guardado',
  saveThreadDoneTemplate: 'Enviamos-te um e-mail para {email} se houver novidades aqui.',
  emailPlaceholder: 'tu@empresa.pt',
  composerPlaceholder: 'Escreve uma mensagem…',
  defaultEyebrow: 'Com tecnologia Munin',
  defaultGreeting: 'Olá. Como podemos ajudar?',
  defaultTitle: 'Conversa connosco',
  welcomeRepliesInstantly: 'Responde de imediato',
  startConversationLabel: 'Iniciar uma conversa',
  startConversationSub: 'Vamos mobilizar um agente já.',
  conversationsHeader: 'As tuas conversas',
  emptyConversationsTitle: 'Ainda sem conversas',
  emptyConversationsSub: 'Inicia uma acima e aparecerá aqui da próxima vez.',
  poweredBy: 'Com tecnologia',
  defaultAuthorName: 'Agente',
  roleAi: 'IA',
  roleHuman: 'humano',
  timeNow: 'agora',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} d',
  timeWeek: '{n} sem',
  timeMonth: '{n} mês',
  voiceCallLabel: 'Ligar',
  voiceStartAriaLabel: 'Iniciar chamada de voz',
  voiceEndAriaLabel: 'Terminar chamada de voz',
  voiceMinimizeAriaLabel: 'Voltar ao chat (manter chamada ativa)',
  voiceResumeAriaLabel: 'Voltar à chamada',
  voiceConnecting: 'A ligar…',
  voiceLive: 'Em direto',
  voiceHint: 'A voz passa por este widget — sem número, sem app.',
  voiceMute: 'Silenciar',
  voiceMuted: 'Silenciado',
  voiceEnd: 'Terminar',
  voiceBackToChat: 'Voltar ao chat',
  voiceOnCallWithTemplate: 'Em chamada com {who}',
  voiceTapToReturn: 'Toca para voltar',
  voiceFailed: 'Falhou a chamada de voz',
  productViewLabel: 'Ver',
  attachAriaLabel: 'Anexar uma imagem',
  attachDropHint: 'Solte a imagem aqui',
  attachUploading: 'A enviar…',
  attachFailed: 'A imagem não foi enviada. Tente de novo.',
  attachRemoveAriaLabel: 'Remover a imagem',
  attachTooMany: 'Pode anexar até {n} imagens.',
  attachTypeRejected: 'Aceitamos PNG, JPEG, GIF e WebP.',
  attachTooLarge: 'As imagens têm de ter menos de {n} MB.',
  attachmentUnavailable: 'Imagem já não disponível',
  lightboxCloseAriaLabel: 'Fechar a imagem',
};

export default pt;
