import type { Strings } from './types.ts';

const ro: Strings = {
  launcherAriaLabel: 'Deschide chatul',
  closeAriaLabel: 'Închide',
  backAriaLabel: 'Înapoi',
  messageAriaLabel: 'Mesaj',
  sendAriaLabel: 'Trimite',
  agentTypingAriaLabel: 'Agentul scrie',
  newConversation: 'Conversație nouă',
  conversation: 'Conversație',
  onlineNow: 'Online acum',
  defaultTeammateName: 'Coleg de echipă',
  typicallyReplies: 'răspunde de obicei în câteva minute',
  statusReconnecting: 'Se reconectează…',
  statusDisconnected: 'Deconectat.',
  saveThreadEyebrow: 'Salvați această conversație',
  saveThreadBlurb: 'Lăsați o adresă de e-mail și păstrăm conversația dacă închideți fereastra.',
  saveThreadCta: 'Salvează →',
  saveThreadSkip: 'Nu acum',
  saveThreadDoneEyebrow: '● Salvat',
  saveThreadDoneTemplate: 'Vă scriem la {email} dacă apare ceva nou aici.',
  emailPlaceholder: 'tu@companie.ro',
  composerPlaceholder: 'Scrieți un mesaj…',
  defaultEyebrow: 'Funcționează cu Munin',
  defaultGreeting: 'Bună. Cu ce vă putem ajuta?',
  defaultTitle: 'Discutați cu noi',
  welcomeRepliesAboutHtml: 'Răspuns în aproximativ <strong>2 min</strong>',
  startConversationLabel: 'Începeți o conversație',
  startConversationSub: 'Punem imediat un agent pe ea.',
  conversationsHeader: 'Conversațiile dumneavoastră',
  emptyConversationsTitle: 'Încă nicio conversație',
  emptyConversationsSub: 'Începeți una mai sus și o găsiți aici data viitoare.',
  poweredBy: 'Funcționează cu',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'om',
  timeNow: 'acum',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} z',
  timeWeek: '{n} săpt',
  timeMonth: '{n} l',
  voiceCallLabel: 'Sună',
  voiceStartAriaLabel: 'Începe apelul vocal',
  voiceEndAriaLabel: 'Încheie apelul vocal',
  voiceMinimizeAriaLabel: 'Înapoi la chat (apelul rămâne activ)',
  voiceResumeAriaLabel: 'Înapoi la apel',
  voiceConnecting: 'Se conectează…',
  voiceLive: 'În direct',
  voiceHint: 'Vocea merge prin acest widget — fără număr de telefon, fără aplicație.',
  voiceMute: 'Oprește microfonul',
  voiceMuted: 'Microfon oprit',
  voiceEnd: 'Încheie',
  voiceBackToChat: 'Înapoi la chat',
  voiceOnCallWithTemplate: 'În apel cu {who}',
  voiceTapToReturn: 'Atingeți pentru a reveni',
  voiceFailed: 'Apelul vocal a eșuat',
  productViewLabel: 'Vezi',
};

export default ro;
