import type { Strings } from './types.ts';

const sk: Strings = {
  launcherAriaLabel: 'Otvoriť chat',
  closeAriaLabel: 'Zavrieť',
  backAriaLabel: 'Späť',
  messageAriaLabel: 'Správa',
  sendAriaLabel: 'Odoslať',
  agentTypingAriaLabel: 'Agent píše',
  newConversation: 'Nová konverzácia',
  conversation: 'Konverzácia',
  onlineNow: 'Práve online',
  defaultTeammateName: 'Člen tímu',
  typicallyReplies: 'obvykle odpovie do niekoľkých minút',
  statusReconnecting: 'Znova sa pripájam…',
  statusDisconnected: 'Odpojené.',
  saveThreadEyebrow: 'Uložiť túto konverzáciu',
  saveThreadBlurb: 'Nechajte nám e-mail a konverzáciu uložíme, aj keď okno zavriete.',
  saveThreadCta: 'Uložiť →',
  saveThreadSkip: 'Teraz nie',
  saveThreadDoneEyebrow: '● Uložené',
  saveThreadDoneTemplate: 'Napíšeme vám na {email}, ak sa tu objaví niečo nové.',
  emailPlaceholder: 'vy@firma.sk',
  composerPlaceholder: 'Napíšte správu…',
  defaultEyebrow: 'Beží na Munin',
  defaultGreeting: 'Dobrý deň. Ako môžeme pomôcť?',
  defaultTitle: 'Napíšte nám',
  welcomeRepliesAboutHtml: 'Odpoveď asi za <strong>2 min</strong>',
  startConversationLabel: 'Začať konverzáciu',
  startConversationSub: 'Hneď sa do toho pustí agent.',
  conversationsHeader: 'Vaše konverzácie',
  emptyConversationsTitle: 'Zatiaľ žiadne konverzácie',
  emptyConversationsSub: 'Začnite vyššie a nabudúce ju nájdete tu.',
  poweredBy: 'Beží na',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'človek',
  timeNow: 'teraz',
  timeMin: '{n} min',
  timeHour: '{n} h',
  timeDay: '{n} d',
  timeWeek: '{n} týž',
  timeMonth: '{n} mes',
  voiceCallLabel: 'Zavolať',
  voiceStartAriaLabel: 'Začať hlasový hovor',
  voiceEndAriaLabel: 'Ukončiť hlasový hovor',
  voiceMinimizeAriaLabel: 'Späť do chatu (hovor zostane aktívny)',
  voiceResumeAriaLabel: 'Späť do hovoru',
  voiceConnecting: 'Pripájam…',
  voiceLive: 'Live',
  voiceHint: 'Hlas ide cez tento widget — žiadne telefónne číslo, žiadna aplikácia.',
  voiceMute: 'Stlmiť',
  voiceMuted: 'Stlmené',
  voiceEnd: 'Ukončiť',
  voiceBackToChat: 'Späť do chatu',
  voiceOnCallWithTemplate: 'Hovor: {who}',
  voiceTapToReturn: 'Ťuknutím sa vrátite',
  voiceFailed: 'Hlasový hovor sa nepodaril',
  productViewLabel: 'Zobraziť',
};

export default sk;
