import type { Strings } from './types.js';

const sv: Strings = {
  launcherAriaLabel: 'Öppna chatt',
  closeAriaLabel: 'Stäng',
  backAriaLabel: 'Tillbaka',
  messageAriaLabel: 'Meddelande',
  sendAriaLabel: 'Skicka',
  agentTypingAriaLabel: 'Agenten skriver',
  newConversation: 'Ny konversation',
  conversation: 'Konversation',
  onlineNow: 'Online nu',
  defaultTeammateName: 'Teammedlem',
  typicallyReplies: 'svarar oftast inom några minuter',
  statusReconnecting: 'Återansluter…',
  statusDisconnected: 'Frånkopplad.',
  saveThreadEyebrow: 'Spara denna konversation',
  saveThreadBlurb: 'Lämna din e-post, så sparar vi konversationen om du stänger fönstret.',
  saveThreadCta: 'Spara →',
  saveThreadSkip: 'Inte nu',
  saveThreadDoneEyebrow: '● Sparad',
  saveThreadDoneTemplate: 'Vi mejlar dig på {email} om något nytt händer här.',
  emailPlaceholder: 'du@foretag.se',
  composerPlaceholder: 'Skriv ett meddelande…',
  defaultEyebrow: 'Drivs av Munin',
  defaultGreeting: 'Hej. Vad kan vi hjälpa till med?',
  defaultTitle: 'Chatta med oss',
  welcomeRepliesAboutHtml: 'Svar inom ca <strong>2 min</strong>',
  startConversationLabel: 'Starta en konversation',
  startConversationSub: 'Vi sätter en agent på det direkt.',
  conversationsHeader: 'Dina konversationer',
  emptyConversationsTitle: 'Inga konversationer ännu',
  emptyConversationsSub: 'Starta en ovan, så dyker den upp här nästa gång.',
  poweredBy: 'Drivs av',
  defaultAuthorName: 'Agent',
  roleAi: 'AI',
  roleHuman: 'människa',
  timeNow: 'nu',
  timeMin: '{n}m',
  timeHour: '{n}t',
  timeDay: '{n}d',
  timeWeek: '{n}v',
  timeMonth: '{n}mån',
  voiceCallLabel: 'Ring',
  voiceStartAriaLabel: 'Starta röstsamtal',
  voiceEndAriaLabel: 'Avsluta röstsamtal',
  voiceMinimizeAriaLabel: 'Tillbaka till chatten (behåll samtalet aktivt)',
  voiceResumeAriaLabel: 'Tillbaka till samtalet',
  voiceConnecting: 'Ansluter…',
  voiceLive: 'Live',
  voiceHint: 'Rösten går genom denna widget — inget telefonnummer, ingen app.',
  voiceMute: 'Tysta',
  voiceMuted: 'Tystad',
  voiceEnd: 'Avsluta',
  voiceBackToChat: 'Tillbaka till chatten',
  voiceOnCallWithTemplate: 'I samtal med {who}',
  voiceTapToReturn: 'Tryck för att återgå',
  voiceFailed: 'Röstsamtal misslyckades',
};

export default sv;
