import type { SeoLanguage, SeoMarket } from './seo-markets.ts';

export const DATAFORSEO_LOCATION_CODES: Record<SeoMarket, number> = {
  albania: 2008,
  andorra: 2020,
  antigua_and_barbuda: 2028,
  armenia: 2051,
  austria: 2040,
  azerbaijan: 2031,
  bahamas: 2044,
  barbados: 2052,
  belgium: 2056,
  belize: 2084,
  bosnia_and_herzegovina: 2070,
  bulgaria: 2100,
  canada: 2124,
  caribbean_netherlands: 2535,
  costa_rica: 2188,
  croatia: 2191,
  curacao: 2531,
  cyprus: 2196,
  czechia: 2203,
  denmark: 2208,
  dominica: 2212,
  dominican_republic: 2214,
  el_salvador: 2222,
  estonia: 2233,
  finland: 2246,
  france: 2250,
  georgia: 2268,
  germany: 2276,
  greece: 2300,
  grenada: 2308,
  guatemala: 2320,
  guernsey: 2831,
  haiti: 2332,
  honduras: 2340,
  hungary: 2348,
  iceland: 2352,
  ireland: 2372,
  isle_of_man: 2833,
  italy: 2380,
  jamaica: 2388,
  jersey: 2832,
  latvia: 2428,
  liechtenstein: 2438,
  lithuania: 2440,
  luxembourg: 2442,
  malta: 2470,
  mexico: 2484,
  moldova: 2498,
  monaco: 2492,
  montenegro: 2499,
  netherlands: 2528,
  nicaragua: 2558,
  north_macedonia: 2807,
  norway: 2578,
  panama: 2591,
  poland: 2616,
  portugal: 2620,
  romania: 2642,
  saint_kitts_and_nevis: 2659,
  saint_lucia: 2662,
  saint_martin: 2663,
  saint_pierre_and_miquelon: 2666,
  saint_vincent_and_the_grenadines: 2670,
  san_marino: 2674,
  serbia: 2688,
  sint_maarten: 2534,
  slovakia: 2703,
  slovenia: 2705,
  spain: 2724,
  sweden: 2752,
  switzerland: 2756,
  trinidad_and_tobago: 2780,
  turkey: 2792,
  ukraine: 2804,
  united_kingdom: 2826,
  united_states: 2840,
  vatican_city: 2336,
};

export const DATAFORSEO_LABS_LANGUAGES: Partial<Record<SeoMarket, readonly SeoLanguage[]>> = {
  albania: ['albanian'],
  armenia: ['armenian'],
  austria: ['german'],
  azerbaijan: ['azerbaijani'],
  belgium: ['dutch', 'french', 'german'],
  bosnia_and_herzegovina: ['bosnian'],
  bulgaria: ['bulgarian'],
  canada: ['english', 'french'],
  costa_rica: ['spanish'],
  croatia: ['croatian'],
  cyprus: ['greek', 'english'],
  czechia: ['czech'],
  denmark: ['danish'],
  el_salvador: ['spanish'],
  estonia: ['estonian'],
  finland: ['finnish'],
  france: ['french'],
  germany: ['german'],
  greece: ['greek', 'english'],
  guatemala: ['spanish'],
  hungary: ['hungarian'],
  ireland: ['english'],
  italy: ['italian'],
  latvia: ['latvian'],
  lithuania: ['lithuanian'],
  malta: ['english'],
  mexico: ['spanish'],
  moldova: ['romanian'],
  monaco: ['french'],
  netherlands: ['dutch'],
  nicaragua: ['spanish'],
  north_macedonia: ['macedonian'],
  norway: ['norwegian'],
  panama: ['spanish'],
  poland: ['polish'],
  portugal: ['portuguese'],
  romania: ['romanian'],
  serbia: ['serbian'],
  slovakia: ['slovak'],
  slovenia: ['slovenian'],
  spain: ['spanish'],
  sweden: ['swedish'],
  switzerland: ['german', 'french', 'italian'],
  turkey: ['turkish'],
  ukraine: ['ukrainian', 'russian'],
  united_kingdom: ['english'],
  united_states: ['english', 'spanish'],
};

export const DATAFORSEO_LANGUAGE_CODES: Record<
  SeoLanguage,
  { serp: string; labs: string | null }
> = {
  albanian: { serp: 'sq', labs: 'sq' },
  armenian: { serp: 'hy', labs: 'hy' },
  azerbaijani: { serp: 'az', labs: 'az' },
  bosnian: { serp: 'bs', labs: 'bs' },
  bulgarian: { serp: 'bg', labs: 'bg' },
  catalan: { serp: 'ca', labs: null },
  croatian: { serp: 'hr', labs: 'hr' },
  czech: { serp: 'cs', labs: 'cs' },
  danish: { serp: 'da', labs: 'da' },
  dutch: { serp: 'nl', labs: 'nl' },
  english: { serp: 'en', labs: 'en' },
  estonian: { serp: 'et', labs: 'et' },
  finnish: { serp: 'fi', labs: 'fi' },
  french: { serp: 'fr', labs: 'fr' },
  georgian: { serp: 'ka', labs: null },
  german: { serp: 'de', labs: 'de' },
  greek: { serp: 'el', labs: 'el' },
  haitian_creole: { serp: 'ht', labs: null },
  hungarian: { serp: 'hu', labs: 'hu' },
  icelandic: { serp: 'is', labs: null },
  irish: { serp: 'ga', labs: null },
  italian: { serp: 'it', labs: 'it' },
  latvian: { serp: 'lv', labs: 'lv' },
  lithuanian: { serp: 'lt', labs: 'lt' },
  macedonian: { serp: 'mk', labs: 'mk' },
  maltese: { serp: 'mt', labs: null },
  norwegian: { serp: 'no', labs: 'nb' },
  polish: { serp: 'pl', labs: 'pl' },
  portuguese: { serp: 'pt', labs: 'pt' },
  romanian: { serp: 'ro', labs: 'ro' },
  russian: { serp: 'ru', labs: 'ru' },
  serbian: { serp: 'sr', labs: 'sr' },
  slovak: { serp: 'sk', labs: 'sk' },
  slovenian: { serp: 'sl', labs: 'sl' },
  spanish: { serp: 'es', labs: 'es' },
  swedish: { serp: 'sv', labs: 'sv' },
  turkish: { serp: 'tr', labs: 'tr' },
  ukrainian: { serp: 'uk', labs: 'uk' },
  welsh: { serp: 'cy', labs: null },
};
