export const MUNIN_VERSION = '0.0.1';

export {
  SmtpOutboundSchema,
  MailerOutboundSchema,
  OutboundConfigSchema,
  ImapInboundSchema,
  SendLimitsSchema,
  type SendLimits,
  EmailChannelConfigInput,
  type EmailChannelConfigInputT,
  CreateWidgetBody,
  type CreateWidgetBodyT,
  UpdateWidgetBody,
  type UpdateWidgetBodyT,
  SetupEmailBody,
  type SetupEmailBodyT,
  SendEmailTestBody,
  type SendEmailTestBodyT,
  ConfigureTwilioSmsBody,
  type ConfigureTwilioSmsBodyT,
  SendTwilioSmsTestBody,
  type SendTwilioSmsTestBodyT,
  ConfigureMessageBirdSmsBody,
  type ConfigureMessageBirdSmsBodyT,
  SendMessageBirdSmsTestBody,
  type SendMessageBirdSmsTestBodyT,
  ConfigureVapiBody,
  type ConfigureVapiBodyT,
  VapiCallInitiateBody,
  type VapiCallInitiateBodyT,
} from './channels.js';
export {
  KNOWN_SKILL_URIS,
  WEB_SCRAPE_SITE_TASK_URI,
  jobKindOf,
  tierFor,
  toolPrefixesFor,
  type JobKind,
  type ModelTier,
} from './job-catalog.js';
