export const MUNIN_VERSION = '0.0.1';

export {
  SmtpOutboundSchema,
  MailerOutboundSchema,
  OutboundConfigSchema,
  ImapInboundSchema,
  SendLimitsSchema,
  type SendLimits,
  EmailChannelConfigInput,
  type EmailChannelConfigInputT,
  CreateWidgetBody,
  type CreateWidgetBodyT,
  UpdateWidgetBody,
  type UpdateWidgetBodyT,
  SetupEmailBody,
  type SetupEmailBodyT,
  SendEmailTestBody,
  type SendEmailTestBodyT,
  ConfigureTwilioSmsBody,
  type ConfigureTwilioSmsBodyT,
  SendTwilioSmsTestBody,
  type SendTwilioSmsTestBodyT,
  ConfigureMessageBirdSmsBody,
  type ConfigureMessageBirdSmsBodyT,
  SendMessageBirdSmsTestBody,
  type SendMessageBirdSmsTestBodyT,
  ConfigureVapiBody,
  type ConfigureVapiBodyT,
  VapiCallInitiateBody,
  type VapiCallInitiateBodyT,
  ConfigureThrellBody,
  type ConfigureThrellBodyT,
  ChannelListOptionsBody,
  type ChannelListOptionsBodyT,
  ThrellCallInitiateBody,
  type ThrellCallInitiateBodyT,
  ConfigureChannelBody,
  type ConfigureChannelBodyT,
  ChannelVoiceCallBody,
  type ChannelVoiceCallBodyT,
  ChannelSendTestBody,
  type ChannelSendTestBodyT,
} from './channels.ts';
export {
  CreateTrackerBody,
  type CreateTrackerBodyT,
  UpdateTrackerBody,
  type UpdateTrackerBodyT,
} from './trackers.ts';
export { sensitive, isSensitiveSchema } from './sensitive.ts';
export {
  KNOWN_SKILL_URIS,
  KNOWN_TASK_URIS,
  WEB_SCRAPE_SITE_TASK_URI,
  jobKindOf,
  tierFor,
  toolPrefixesFor,
  priorityFor,
  type JobKind,
  type ModelTier,
} from './job-catalog.ts';
export {
  CMS_EVENT_TYPES,
  CRM_EVENT_TYPES,
  KB_EVENT_TYPES,
  CONVERSATION_EVENT_TYPES,
  OUTREACH_EVENT_TYPES,
  SYSTEM_EVENT_TYPES,
  EVENT_TYPES_BY_MODULE,
  KNOWN_EVENT_TYPES,
  isKnownEventType,
  type KnownEventType,
  type EventModule,
} from './event-catalog.ts';
