export const SUPPORTED_SCOPES = [
  'mcp:tools',
  'mcp:admin',
  'identity:read',
  'kb:read',
  'kb:write',
  'conv:read',
  'conv:write',
  'crm:read',
  'crm:write',
  'cms:read',
  'cms:write',
  'outreach:read',
  'outreach:write',
  'connectors:read',
  'connectors:write',
  'commerce:read',
  'bookings:read',
  'bookings:write',
  'seo:read',
  'seo:write',
  'analytics:read',
  'analytics:write',
  'webhooks:read',
  'webhooks:write',
  'feedback:read',
  'feedback:write',
  'system_alerts:read',
  'system_alerts:write',
  'slack:read',
  'slack:write',
  'social:read',
  'social:write',
] as const;

export type SupportedScope = (typeof SUPPORTED_SCOPES)[number];
